create extension if not exists "uuid-ossp";

create table if not exists "country"
(
    id            UUID unique        not null default uuid_generate_v1() primary key,
    name          varchar(50) unique not null,
    code          varchar(3)         not null,
    date          date
);

alter table "country"
    owner to postgres;

delete from "country";

insert into "country"(name, code, date) values('Fiji', 'FJ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Tanzania', 'TZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Western Sahara', 'EH', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Canada', 'CA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('United States', 'US', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Kazakhstan', 'KZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Uzbekistan', 'UZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Papua New Guinea', 'PG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Indonesia', 'ID', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Argentina', 'AR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Chile', 'CL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Democratic Republic of the Congo', 'CD', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Somalia', 'SO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Kenya', 'KE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Sudan', 'SD', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Chad', 'TD', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Haiti', 'HT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Dominican Republic', 'DO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Russia', 'RU', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Bahamas', 'BS', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Falkland Islands', 'FK', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Norway', 'NO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Greenland', 'GL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Timor-Leste', 'TL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('South Africa', 'ZA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Lesotho', 'LS', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Mexico', 'MX', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Uruguay', 'UY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Brazil', 'BR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Bolivia', 'BO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Peru', 'PE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Colombia', 'CO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Panama', 'PA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Costa Rica', 'CR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Nicaragua', 'NI', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Honduras', 'HN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('El Salvador', 'SV', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Guatemala', 'GT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Belize', 'BZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Venezuela', 'VE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Guyana', 'GY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Suriname', 'SR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('France', 'FR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Ecuador', 'EC', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Puerto Rico', 'PR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Jamaica', 'JM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Cuba', 'CU', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Zimbabwe', 'ZW', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Botswana', 'BW', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Namibia', 'NA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Senegal', 'SN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Mali', 'ML', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Mauritania', 'MR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Benin', 'BJ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Niger', 'NE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Nigeria', 'NG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Cameroon', 'CM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Togo', 'TG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Ghana', 'GH', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Cote dIvoire', 'CI', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Guinea', 'GN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Guinea-Bissau', 'GW', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Liberia', 'LR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Sierra Leone', 'SL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Burkina Faso', 'BF', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Central African Republic', 'CF', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Republic of the Congo', 'CG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Gabon', 'GA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Equatorial Guinea', 'GQ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Zambia', 'ZM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Malawi', 'MW', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Mozambique', 'MZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Eswatini', 'SZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Angola', 'AO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Burundi', 'BI', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Israel', 'IL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Lebanon', 'LB', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Madagascar', 'MG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Palestine', 'PS', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('The Gambia', 'GM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Tunisia', 'TN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Algeria', 'DZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Jordan', 'JO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('United Arab Emirates', 'AE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Qatar', 'QA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Kuwait', 'KW', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Iraq', 'IQ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Oman', 'OM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Vanuatu', 'VU', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Cambodia', 'KH', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Thailand', 'TH', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Lao PDR', 'LA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Myanmar', 'MM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Vietnam', 'VN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Dem. Rep. Korea', 'KP', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Republic of Korea', 'KR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Mongolia', 'MN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('India', 'IN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Bangladesh', 'BD', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Bhutan', 'BT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Nepal', 'NP', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Pakistan', 'PK', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Afghanistan', 'AF', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Tajikistan', 'TJ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Kyrgyzstan', 'KG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Turkmenistan', 'TM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Iran', 'IR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Syria', 'SY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Armenia', 'AM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Sweden', 'SE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Belarus', 'BY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Ukraine', 'UA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Poland', 'PL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Austria', 'AT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Hungary', 'HU', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Moldova', 'MD', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Romania', 'RO', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Lithuania', 'LT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Latvia', 'LV', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Estonia', 'EE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Germany', 'DE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Bulgaria', 'BG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Greece', 'GR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Turkey', 'TR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Albania', 'AL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Croatia', 'HR', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Switzerland', 'CH', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Luxembourg', 'LU', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Belgium', 'BE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Netherlands', 'NL', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Portugal', 'PT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Spain', 'ES', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Ireland', 'IE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('New Caledonia', 'NC', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Solomon Islands', 'SB', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('New Zealand', 'NZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Australia', 'AU', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Sri Lanka', 'LK', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('China', 'CN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Taiwan', 'TW', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Italy', 'IT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Denmark', 'DK', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('United Kingdom', 'GB', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Iceland', 'IS', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Azerbaijan', 'AZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Georgia', 'GE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Philippines', 'PH', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Malaysia', 'MY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Brunei Darussalam', 'BN', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Slovenia', 'SI', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Finland', 'FI', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Slovakia', 'SK', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Czech Republic', 'CZ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Eritrea', 'ER', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Japan', 'JP', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Paraguay', 'PY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Yemen', 'YE', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Saudi Arabia', 'SA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Northern Cyprus', 'CYP', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Cyprus', 'CY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Morocco', 'MA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Egypt', 'EG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Libya', 'LY', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Ethiopia', 'ET', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Djibouti', 'DJ', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Somaliland', 'SOM', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Uganda', 'UG', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Rwanda', 'RW', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Bosnia and Herzegovina', 'BA', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Macedonia', 'MK', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Serbia', 'RS', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Montenegro', 'ME', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Kosovo', 'XK', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('Trinidad and Tobago', 'TT', CURRENT_TIMESTAMP);
insert into "country"(name, code, date) values('South Sudan', 'SS', CURRENT_TIMESTAMP);